# Generated by Django 4.2.27 on 2026-01-07 22:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, help_text='DNI / Pasaporte', max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('GENERAL', 'Aviso general'), ('ASSETS', 'Informe de activos'), ('WELCOME', 'Documento de bienvenida'), ('MONTHLY', 'Informe mensual')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('ERROR', 'Error')], default='DRAFT', max_length=10)),
                ('investor', models.ForeignKey(blank=True, help_text='Inversor al que pertenece el aviso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('participations', models.DecimalField(decimal_places=6, max_digits=15)),
                ('nav_price', models.DecimalField(decimal_places=6, help_text='Precio NAV aplicado en la operación', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe total (€)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Referencia externa / IB / bancaria', max_length=64)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to='investors.investor')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvestorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participations', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_positions', to='investors.investor')),
            ],
            options={
                'unique_together': {('investor', 'fund')},
            },
        ),
    ]
