# Generated by Django 4.2.27 on 2025-12-13 17:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_alter_fund_options_remove_fund_nav_and_more'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='document_id',
            field=models.CharField(help_text='DNI / Pasaporte', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='InvestorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participations', models.DecimalField(decimal_places=6, default=Decimal('0.0'), help_text='Participaciones del fondo', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_positions', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Participación en fondo',
                'verbose_name_plural': 'Participaciones en fondos',
                'unique_together': {('investor', 'fund')},
            },
        ),
    ]
