# Generated by Django 4.2.27 on 2026-01-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='nav_price',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
