# Generated by Django 4.2.29 on 2026-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_investorfundtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección física', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
