# Generated by Django 4.2.27 on 2025-12-28 22:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_alter_fund_products'),
        ('investors', '0002_alter_investor_document_id_investorfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorfund',
            name='average_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='investorfund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investorfund',
            name='participations',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.CreateModel(
            name='InvestorFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('participations', models.DecimalField(decimal_places=6, max_digits=15)),
                ('nav_price', models.DecimalField(decimal_places=6, help_text='Precio NAV aplicado en la operación', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe total (€)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Referencia externa / IB / bancaria', max_length=64)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to='investors.investor')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
