# Generated by Django 4.2.27 on 2025-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_investorfund_average_price_investorfund_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='document_id',
            field=models.CharField(blank=True, help_text='DNI / Pasaporte', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', max_length=20, null=True),
        ),
    ]
