# Generated by Django 4.2.29 on 2026-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_investor_address_investor_city_investor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='client_code',
            field=models.CharField(blank=True, help_text='Código estratégico de cliente (ej: INV-501)', max_length=20, null=True, unique=True),
        ),
    ]
