# Generated by Django 4.2.27 on 2026-01-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_alter_investor_document_id_alter_investor_risk_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorfund',
            options={},
        ),
    ]
