# Generated by Django 4.2.29 on 2026-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_investor_client_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Inversor', 'verbose_name_plural': 'Inversores'},
        ),
        migrations.AlterModelOptions(
            name='investorfund',
            options={'verbose_name': 'Participación de Inversor', 'verbose_name_plural': 'Participaciones de Inversores'},
        ),
        migrations.AlterModelOptions(
            name='investorfundtransaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Transacción de Inversor', 'verbose_name_plural': 'Transacciones de Inversores'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
