# Generated by Django 4.2.29 on 2026-04-02 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_investor_options_alter_investorfund_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorfund',
            name='average_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='investorfund',
            name='participations',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='nav_price',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='participations',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
