# Generated by Django 4.2.27 on 2026-01-05 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_alter_investorfund_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.CharField(choices=[('GENERAL', 'Aviso general'), ('ASSETS', 'Informe de activos'), ('WELCOME', 'Documento de bienvenida'), ('MONTHLY', 'Informe mensual')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('ERROR', 'Error')], default='DRAFT', max_length=10)),
                ('investor', models.ForeignKey(blank=True, help_text='Inversor al que pertenece el aviso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investors.investor')),
            ],
        ),
    ]
