# Generated by Django 4.2.29 on 2026-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_alter_investorfund_average_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorfundtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('BONUS', 'Bonus')], max_length=8),
        ),
    ]
