# Generated by Django 4.2.29 on 2026-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_alter_investorfundtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(choices=[('GENERAL', 'Aviso general'), ('ASSETS', 'Informe de activos'), ('WELCOME', 'Documento de bienvenida'), ('MONTHLY', 'Informe mensual'), ('BUY_REPORT', 'Reporte de compra'), ('SELL_REPORT', 'Reporte de venta')], max_length=20),
        ),
    ]
