# Generated by Django 4.2.29 on 2026-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0009_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'Comunicado General'), ('INFO', 'Informativo'), ('URGENT', 'Aviso Urgente'), ('ACTION', 'Acción requerida'), ('OPPORTUNITY', 'Oportunidad de Inversión'), ('REPORT', 'Reporte de Rendimiento'), ('MEETING', 'Solicitud de Reunión'), ('TAX', 'Fiscal / Legal'), ('OTHER', 'Otros')], default='INFO', max_length=20),
        ),
    ]
