# Generated by Django 4.2.29 on 2026-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0010_alter_communication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='communications/attachments/', verbose_name='Documento adjunto'),
        ),
    ]
