# Generated by Django 4.2.27 on 2026-01-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.CharField(max_length=32)),
                ('net_liquidation', models.DecimalField(decimal_places=2, help_text='Valor total de la cuenta', max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, help_text='Efectivo disponible', max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, help_text='Valor de posiciones abiertas', max_digits=20)),
                ('margin_used', models.DecimalField(blank=True, decimal_places=2, help_text='Margen utilizado (si aplica)', max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IBPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('currency', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='ib.ibsnapshot')),
            ],
        ),
    ]
