# Generated by Django 4.2.29 on 2026-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ibposition',
            options={'verbose_name': 'Posición IB', 'verbose_name_plural': 'Posiciones IB'},
        ),
        migrations.AlterModelOptions(
            name='ibsnapshot',
            options={'verbose_name': 'Snapshot IB', 'verbose_name_plural': 'Snapshots IB'},
        ),
    ]
