# Generated by Django 5.2.9 on 2025-12-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('STOCK', 'Acciones'), ('ETF', 'ETF'), ('FUND', 'Fondo de inversión'), ('CRYPTO', 'Criptomonedas'), ('COMMODITY', 'Materias primas'), ('BOND', 'Bonos')], max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
