# Generated by Django 4.2.27 on 2026-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_map',
            field=models.BooleanField(default=True),
        ),
    ]
