# Generated by Django 4.2.27 on 2026-01-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_show_in_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.RemoveField(
            model_name='country',
            name='market_type',
        ),
    ]
