# Generated by Django 4.2.27 on 2025-12-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_current_price_product_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afganistán'), ('AL', 'Albania'), ('DZ', 'Argelia'), ('AS', 'Samoa Americana'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguila'), ('AQ', 'Antártida'), ('AG', 'Antigua y Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaiyán'), ('BS', 'Bahamas'), ('BH', 'Baréin'), ('BD', 'Bangladés'), ('BB', 'Barbados'), ('BY', 'Bielorrusia'), ('BE', 'Bélgica'), ('BZ', 'Belice'), ('BJ', 'Benín'), ('BM', 'Bermudas'), ('BT', 'Bután'), ('BO', 'Bolivia'), ('BA', 'Bosnia y Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('IO', 'Territorio Británico del Océano Índico'), ('BN', 'Brunéi'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Camboya'), ('CM', 'Camerún'), ('CA', 'Canadá'), ('CV', 'Cabo Verde'), ('KY', 'Islas Caimán'), ('CF', 'República Centroafricana'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoras'), ('CG', 'Congo'), ('CR', 'Costa Rica'), ('HR', 'Croacia'), ('CU', 'Cuba'), ('CY', 'Chipre'), ('CZ', 'Chequia'), ('DK', 'Dinamarca'), ('DJ', 'Yibuti'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('EG', 'Egipto'), ('SV', 'El Salvador'), ('EE', 'Estonia'), ('ET', 'Etiopía'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GA', 'Gabón'), ('GE', 'Georgia'), ('DE', 'Alemania'), ('GH', 'Ghana'), ('GR', 'Grecia'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungría'), ('IS', 'Islandia'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Irán'), ('IQ', 'Irak'), ('IE', 'Irlanda'), ('IL', 'Israel'), ('IT', 'Italia'), ('JM', 'Jamaica'), ('JP', 'Japón'), ('JO', 'Jordania'), ('KZ', 'Kazajistán'), ('KE', 'Kenia'), ('KW', 'Kuwait'), ('LV', 'Letonia'), ('LB', 'Líbano'), ('LY', 'Libia'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MY', 'Malasia'), ('MX', 'México'), ('MA', 'Marruecos'), ('NL', 'Países Bajos'), ('NZ', 'Nueva Zelanda'), ('NG', 'Nigeria'), ('NO', 'Noruega'), ('PK', 'Pakistán'), ('PA', 'Panamá'), ('PE', 'Perú'), ('PH', 'Filipinas'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('QA', 'Catar'), ('RO', 'Rumanía'), ('RU', 'Rusia'), ('SA', 'Arabia Saudí'), ('SG', 'Singapur'), ('ZA', 'Sudáfrica'), ('KR', 'Corea del Sur'), ('ES', 'España'), ('SE', 'Suecia'), ('CH', 'Suiza'), ('TH', 'Tailandia'), ('TR', 'Turquía'), ('UA', 'Ucrania'), ('AE', 'Emiratos Árabes Unidos'), ('GB', 'Reino Unido'), ('US', 'Estados Unidos'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('ZW', 'Zimbabue'), ('GLOBAL', 'Global')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='industry',
            field=models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('SEMICONDUCTORS', 'Semiconductores'), ('BANKS', 'Banca'), ('INSURANCE', 'Seguros'), ('PHARMA', 'Farmacéutica'), ('OIL_GAS', 'Petróleo y gas'), ('RENEWABLES', 'Energías renovables'), ('RETAIL', 'Retail')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'Europa'), ('NA', 'Norteamérica'), ('SA', 'Sudamérica'), ('ASIA', 'Asia'), ('AF', 'África'), ('OCE', 'Oceanía'), ('GLOBAL', 'Global')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sector',
            field=models.CharField(blank=True, choices=[('TECH', 'Tecnología'), ('FIN', 'Finanzas'), ('HEALTH', 'Salud'), ('ENERGY', 'Energía'), ('INDUSTRIAL', 'Industrial'), ('CONSUMER', 'Consumo'), ('UTILITIES', 'Servicios públicos'), ('REAL_ESTATE', 'Inmobiliario'), ('MATERIALS', 'Materiales')], max_length=20, null=True),
        ),
    ]
