# Generated by Django 4.2.29 on 2026-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_country_location_remove_country_market_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclass',
            options={'verbose_name': 'Clase de Activo', 'verbose_name_plural': 'Clases de Activos'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Divisa', 'verbose_name_plural': 'Divisas'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industria', 'verbose_name_plural': 'Industrias'},
        ),
        migrations.AlterModelOptions(
            name='markettype',
            options={'verbose_name': 'Tipo de Mercado', 'verbose_name_plural': 'Tipos de Mercado'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Precio de Producto', 'verbose_name_plural': 'Precios de Productos'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Estrategia', 'verbose_name_plural': 'Estrategias'},
        ),
    ]
