# Generated by Django 4.2.29 on 2026-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_assetclass_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='esg_score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
