# Generated by Django 4.2.27 on 2026-01-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('investors', '0001_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta'), ('DEPOSIT', 'Depósito'), ('WITHDRAW', 'Retiro')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe aportado o retirado', max_digits=12)),
                ('participations', models.DecimalField(decimal_places=6, help_text='Participaciones generadas o retiradas', max_digits=15)),
                ('participation_value', models.DecimalField(decimal_places=6, help_text='Valor de la participación en ese momento', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('IN', 'Aportación'), ('OUT', 'Retirada')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transactions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Transacción de inversor',
                'verbose_name_plural': 'Transacciones de inversores',
                'ordering': ('-created_at',),
            },
        ),
    ]
