# Generated by Django 4.2.27 on 2025-12-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_investor_document_id_investorfund'),
        ('funds', '0006_alter_fund_options_remove_fund_nav_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Transacción de cartera', 'verbose_name_plural': 'Transacciones de cartera'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Importe total de la transacción', max_digits=12),
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe aportado o retirado', max_digits=12)),
                ('participations', models.DecimalField(decimal_places=6, help_text='Participaciones generadas o retiradas', max_digits=15)),
                ('participation_value', models.DecimalField(decimal_places=6, help_text='Valor de la participación en ese momento', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('IN', 'Aportación'), ('OUT', 'Retirada')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transactions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Transacción de inversor',
                'verbose_name_plural': 'Transacciones de inversores',
                'ordering': ('-created_at',),
            },
        ),
    ]
