# Generated by Django 4.2.27 on 2025-12-13 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_alter_transaction_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
    ]
