# Generated by Django 4.2.27 on 2025-12-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='analysis',
            field=models.TextField(blank=True, help_text='Análisis o notas sobre la transacción'),
        ),
    ]
