# Generated by Django 4.2.27 on 2026-01-21 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_show_in_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código interno o abreviatura (ej: NYSE, NASDAQ)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre visible', max_length=150)),
                ('element_type', models.CharField(choices=[('MARKET', 'Mercado de valores'), ('EXCHANGE', 'Bolsa'), ('CENTRAL_BANK', 'Banco central'), ('FIN_CENTER', 'Centro financiero'), ('REFERENCE', 'Referencia económica'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Ubicación geográfica (lon, lat)', srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_map', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_elements', to='products.country')),
            ],
        ),
    ]
