# Generated by Django 4.2.27 on 2026-01-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código interno (ej: MARKET, CENTRAL_BANK)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nombre visible', max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Icono para el mapa (PNG / SVG recomendado)', null=True, upload_to='map_icons/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Map element type',
                'verbose_name_plural': 'Map element types',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='mapelement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='mapelement',
            name='code',
            field=models.CharField(blank=True, help_text='Código interno o abreviatura (opcional)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mapelement',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='home.mapelementtype'),
        ),
    ]
