# Generated by Django 4.2.27 on 2026-01-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mapelementtype_alter_mapelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelementtype',
            name='code',
            field=models.CharField(blank=True, help_text='Código interno (ej: MARKET, CENTRAL_BANK)', max_length=30, null=True, unique=True),
        ),
    ]
