# Generated by Django 4.2.29 on 2026-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_mapelementtype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapelement',
            options={'ordering': ('name',), 'verbose_name': 'Elemento de Mapa', 'verbose_name_plural': 'Elementos de Mapa'},
        ),
        migrations.AlterModelOptions(
            name='mapelementtype',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Elemento de Mapa', 'verbose_name_plural': 'Tipos de Elementos de Mapa'},
        ),
    ]
