# Generated by Django 5.2.9 on 2025-12-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundRiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(help_text='1 = bajo riesgo, 5 = alto riesgo')),
            ],
            options={
                'verbose_name': 'Nivel de riesgo',
                'verbose_name_plural': 'Niveles de riesgo',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='funds.fundrisklevel')),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
            },
        ),
    ]
