# Generated by Django 4.2.27 on 2026-01-06 01:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDiversification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre visible (ej: Acciones)', max_length=50)),
                ('product_type', models.CharField(choices=[('STOCK', 'Acciones'), ('ETF', 'ETF'), ('COMMODITY', 'Materias primas'), ('BOND', 'Bonos'), ('CASH', 'Liquidez'), ('CRYPTO', 'Criptomonedas')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado (ej: 40.00)', max_digits=5)),
                ('color', models.CharField(default='#3b82f6', help_text='Color HEX para el gráfico (ej: #3b82f6)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en el gráfico')),
            ],
            options={
                'verbose_name': 'Diversificación del fondo',
                'verbose_name_plural': 'Diversificación del fondo',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FundRiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(help_text='1 = bajo riesgo, 5 = alto riesgo')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nivel de riesgo',
                'verbose_name_plural': 'Niveles de riesgo',
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('manager', models.CharField(blank=True, help_text='Gestor del fondo', max_length=100)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar estadounidense'), ('GBP', 'Libra esterlina')], default='EUR', max_length=3)),
                ('nav_actual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='NAV (valor neto de las participaciones)', max_digits=12, null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Indica si el fondo acepta nuevas aportaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
                ('risk_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='funds.fundrisklevel')),
            ],
        ),
        migrations.CreateModel(
            name='FundPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Cantidad total del activo en cartera', max_digits=16)),
                ('avg_price', models.DecimalField(decimal_places=4, help_text='Precio medio de compra', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='funds.fund')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_positions', to='products.product')),
            ],
            options={
                'verbose_name': 'Posición del fondo',
                'verbose_name_plural': 'Posiciones del fondo',
                'unique_together': {('fund', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_value', models.DecimalField(decimal_places=4, help_text='NAV del fondo en la fecha indicada', max_digits=12)),
                ('date', models.DateField(help_text='Fecha efectiva del NAV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_nav_updates', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
            options={
                'verbose_name': 'NAV del fondo',
                'verbose_name_plural': 'Histórico de NAVs',
                'ordering': ('-date',),
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
