# Generated by Django 4.2.27 on 2026-01-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddiversification',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diversification', to='funds.fund'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='funddiversification',
            unique_together={('fund', 'product_type')},
        ),
    ]
