# Generated by Django 5.2.9 on 2025-12-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['name'], 'verbose_name': 'Fondo', 'verbose_name_plural': 'Fondos'},
        ),
        migrations.AlterModelOptions(
            name='fundrisklevel',
            options={'ordering': ['level'], 'verbose_name': 'Nivel de riesgo', 'verbose_name_plural': 'Niveles de riesgo'},
        ),
        migrations.AlterField(
            model_name='fundrisklevel',
            name='level',
            field=models.IntegerField(help_text='Nivel de riesgo de 1 (bajo) a 5 (alto)'),
        ),
    ]
