# Generated by Django 5.2.9 on 2025-12-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_fund_options_alter_fundrisklevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ('name',), 'verbose_name': 'Fondo', 'verbose_name_plural': 'Fondos'},
        ),
        migrations.AlterModelOptions(
            name='fundrisklevel',
            options={'ordering': ('level',), 'verbose_name': 'Nivel de riesgo', 'verbose_name_plural': 'Niveles de riesgo'},
        ),
        migrations.AddField(
            model_name='fund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar estadounidense'), ('GBP', 'Libra esterlina')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='fund',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='manager',
            field=models.CharField(blank=True, help_text='Gestor del fondo', max_length=100),
        ),
        migrations.AddField(
            model_name='fund',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor liquidativo actual (NAV)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='performance_1y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rentabilidad 1 año (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='performance_5y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rentabilidad 5 años (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fundrisklevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fundrisklevel',
            name='level',
            field=models.IntegerField(help_text='1 = bajo riesgo, 5 = alto riesgo'),
        ),
    ]
