# Generated by Django 4.2.27 on 2026-01-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('funds', '0002_funddiversification_fund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='funds.fund')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_trades', to='products.product')),
            ],
        ),
    ]
