# Generated by Django 5.2.9 on 2025-12-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_fund_options_alter_fundrisklevel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Productos financieros que componen este fondo', related_name='funds', to='funds.financialproduct'),
        ),
    ]
