# Generated by Django 4.2.27 on 2026-01-18 20:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0003_fundtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCapitalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del estado de capital')),
                ('capital_interactive_broker', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital total en Interactive Brokers', max_digits=14)),
                ('capital_binance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital total en Binance', max_digits=14)),
                ('nav_participations', models.DecimalField(decimal_places=6, help_text='Número total de participaciones del fondo', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_capital_snapshots', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_snapshots', to='funds.fund')),
            ],
            options={
                'verbose_name': 'Snapshot de capital del fondo',
                'verbose_name_plural': 'Snapshots de capital del fondo',
                'ordering': ('-date',),
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
