# Generated by Django 4.2.27 on 2026-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_fundcapitalsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcapitalsnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del estado de capital'),
        ),
    ]
