# Generated by Django 5.2.9 on 2025-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_financialproduct_fund_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Acción'), ('bond', 'Bono'), ('etf', 'ETF'), ('crypto', 'Criptomoneda'), ('fund', 'Fondo'), ('commodity', 'Materia prima'), ('other', 'Otro')], default='stock', max_length=20),
        ),
    ]
