# Generated by Django 4.2.27 on 2025-12-13 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0005_alter_financialproduct_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={},
        ),
        migrations.RemoveField(
            model_name='fund',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='performance_1y',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='performance_5y',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='products',
        ),
        migrations.AlterField(
            model_name='fund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fund',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Indica si el fondo acepta nuevas aportaciones'),
        ),
        migrations.DeleteModel(
            name='FinancialProduct',
        ),
    ]
