# Generated by Django 4.2.27 on 2026-01-18 20:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_alter_fundcapitalsnapshot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='participations',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Total de participaciones emitidas (auto)', max_digits=15),
        ),
    ]
