# Generated by Django 4.2.27 on 2025-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('funds', '0006_alter_fund_options_remove_fund_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
