# Generated by Django 4.2.27 on 2026-01-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_fund_participations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundcapitalsnapshot',
            name='created_by',
        ),
    ]
