# Generated by Django 4.2.27 on 2025-12-14 20:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_fund_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='nav_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='NAV (valor neto de las participaciones)', max_digits=12, null=True),
        ),
    ]
