# Generated by Django 4.2.29 on 2026-03-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_remove_fundcapitalsnapshot_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundposition',
            options={'verbose_name': 'Posición de Cartera', 'verbose_name_plural': 'Inventario de Cartera'},
        ),
        migrations.AlterModelOptions(
            name='fundrisklevel',
            options={'ordering': ('level',), 'verbose_name': 'Nivel de Riesgo', 'verbose_name_plural': 'Niveles de Riesgo'},
        ),
        migrations.AlterModelOptions(
            name='fundtrade',
            options={'ordering': ('-created_at',), 'verbose_name': 'Operación de Fondo', 'verbose_name_plural': 'Libro Diario de Operaciones'},
        ),
    ]
