# Generated by Django 4.2.27 on 2025-12-20 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0008_fund_nav_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_value', models.DecimalField(decimal_places=4, help_text='NAV del fondo en la fecha indicada', max_digits=12)),
                ('date', models.DateField(help_text='Fecha efectiva del NAV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_nav_updates', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
            options={
                'verbose_name': 'NAV del fondo',
                'verbose_name_plural': 'Histórico de NAVs',
                'ordering': ('-date',),
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
