# Generated by OpenCode on 2026-04-01

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_valor_diario_fondo(apps, schema_editor):
    ValorDiarioFondo = apps.get_model("funds", "ValorDiarioFondo")

    for registro in ValorDiarioFondo.objects.order_by("fecha"):
        capital_ibkr = registro.capital_interactive_broker or Decimal("0")
        capital_binance = registro.capital_binance or Decimal("0")
        participaciones = registro.nav_participations or Decimal("0")

        valor_total = capital_ibkr + capital_binance
        nav = Decimal("0")
        if participaciones > 0:
            nav = (valor_total / participaciones).quantize(Decimal("0.000001"))

        fecha_valor = registro.fecha
        if hasattr(fecha_valor, "date"):
            fecha_valor = fecha_valor.date()

        registro.valor_total = valor_total
        registro.participaciones = participaciones
        registro.nav = nav
        registro.fecha = fecha_valor
        registro.save(update_fields=["valor_total", "participaciones", "nav", "fecha"])


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0008_alter_fundposition_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FundCapitalSnapshot",
            new_name="ValorDiarioFondo",
        ),
        migrations.RenameField(
            model_name="valordiariofondo",
            old_name="date",
            new_name="fecha",
        ),
        migrations.RenameField(
            model_name="valordiariofondo",
            old_name="created_at",
            new_name="creado_en",
        ),
        migrations.AlterField(
            model_name="valordiariofondo",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valores_diarios",
                to="funds.fund",
            ),
        ),
        migrations.AddField(
            model_name="valordiariofondo",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20),
        ),
        migrations.AddField(
            model_name="valordiariofondo",
            name="participaciones",
            field=models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="valordiariofondo",
            name="nav",
            field=models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="valordiariofondo",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="valores_diarios_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_valor_diario_fondo, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="valordiariofondo",
            name="capital_interactive_broker",
        ),
        migrations.RemoveField(
            model_name="valordiariofondo",
            name="capital_binance",
        ),
        migrations.RemoveField(
            model_name="valordiariofondo",
            name="nav_participations",
        ),
        migrations.AlterField(
            model_name="valordiariofondo",
            name="fecha",
            field=models.DateField(help_text="Fecha efectiva del valor del fondo"),
        ),
        migrations.AlterModelOptions(
            name="valordiariofondo",
            options={
                "ordering": ("-fecha",),
                "verbose_name": "Valor diario del fondo",
                "verbose_name_plural": "Valores diarios del fondo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="valordiariofondo",
            unique_together={("fund", "fecha")},
        ),
    ]
