# Generated by OpenCode on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0009_valor_diario_fondo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FundNAV",
        ),
    ]
