# Generated by Django 4.2.29 on 2026-04-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_valor_diario_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valordiariofondo',
            name='nav',
            field=models.DecimalField(decimal_places=6, help_text='NAV del fondo en la fecha indicada', max_digits=20),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='participaciones',
            field=models.DecimalField(decimal_places=6, help_text='Número total de participaciones del fondo', max_digits=20),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, help_text='Valor total del fondo (IBKR + Binance)', max_digits=20),
        ),
    ]
