# Generated by Django 4.2.27 on 2025-12-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_fundnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDiversification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre visible (ej: Acciones)', max_length=50)),
                ('product_type', models.CharField(choices=[('STOCK', 'Acciones'), ('ETF', 'ETF'), ('COMMODITY', 'Materias primas'), ('BOND', 'Bonos'), ('CASH', 'Liquidez'), ('CRYPTO', 'Criptomonedas')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje asignado (ej: 40.00)', max_digits=5)),
                ('color', models.CharField(default='#3b82f6', help_text='Color HEX para el gráfico (ej: #3b82f6)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar en el gráfico')),
            ],
            options={
                'verbose_name': 'Diversificación del fondo',
                'verbose_name_plural': 'Diversificación del fondo',
                'ordering': ('order',),
            },
        ),
    ]
