# Generated by OpenCode on 2026-04-02

from decimal import Decimal

from django.db import migrations, models


def backfill_capital_sources(apps, schema_editor):
    ValorDiarioFondo = apps.get_model("funds", "ValorDiarioFondo")

    for registro in ValorDiarioFondo.objects.all():
        valor_total = registro.valor_total or Decimal("0")
        participaciones = registro.participaciones or Decimal("0")

        registro.capital_interactive_broker = valor_total
        registro.capital_binance = Decimal("0")
        registro.valor_total = valor_total

        if participaciones > 0:
            registro.nav = (valor_total / participaciones).quantize(Decimal("0.000001"))
        else:
            registro.nav = Decimal("0")

        registro.save(
            update_fields=[
                "capital_interactive_broker",
                "capital_binance",
                "valor_total",
                "nav",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0010_remove_fundnav"),
    ]

    operations = [
        migrations.AddField(
            model_name="valordiariofondo",
            name="capital_interactive_broker",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20),
        ),
        migrations.AddField(
            model_name="valordiariofondo",
            name="capital_binance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="valordiariofondo",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="valordiariofondo",
            name="nav",
            field=models.DecimalField(decimal_places=6, default=Decimal("0"), editable=False, max_digits=20),
        ),
        migrations.RunPython(backfill_capital_sources, reverse_code=migrations.RunPython.noop),
    ]
