# Generated by Django 4.2.27 on 2025-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_country_alter_product_industry_and_more'),
        ('funds', '0010_funddiversification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
