# Generated by OpenCode on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0010_alter_valordiariofondo_nav_and_more"),
        ("funds", "0011_valor_diario_fondo_capital"),
    ]

    operations = []
