# Generated by Django 4.2.29 on 2026-04-02 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_merge_valor_diario_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='nav_actual',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0000'), help_text='NAV (valor neto de las participaciones)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='participations',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), help_text='Total de participaciones emitidas (auto)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='funddiversification',
            name='percentage',
            field=models.DecimalField(decimal_places=6, help_text='Porcentaje asignado (ej: 40.0000)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundposition',
            name='avg_price',
            field=models.DecimalField(decimal_places=6, help_text='Precio medio de compra', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundposition',
            name='quantity',
            field=models.DecimalField(decimal_places=6, help_text='Cantidad total del activo en cartera', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundtrade',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='fundtrade',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='capital_binance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), help_text='Capital total en Binance', max_digits=20),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='capital_interactive_broker',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), help_text='Capital total en Interactive Brokers', max_digits=20),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='nav',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), editable=False, help_text='NAV del fondo en la fecha indicada', max_digits=20),
        ),
        migrations.AlterField(
            model_name='valordiariofondo',
            name='valor_total',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), editable=False, help_text='Valor total del fondo (IBKR + Binance)', max_digits=20),
        ),
    ]
