# Generated by Django 4.2.29 on 2026-04-06 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_alter_fund_nav_actual_alter_fund_participations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valordiariofondo',
            name='valor_total',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0000'), editable=False, help_text='Valor total del fondo (Broker + Binance)', max_digits=20),
        ),
    ]
